# Generated by Django 4.1.7 on 2023-04-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelDatasource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=250)),
                ("url", models.CharField(max_length=250)),
                ("token", models.CharField(max_length=250)),
                ("org", models.CharField(max_length=250)),
                ("bucket", models.CharField(max_length=250)),
            ],
            options={
                "db_table": "tbl_datasource",
            },
        ),
    ]
