# Generated by Django 4.1.7 on 2023-04-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0002_modeldetector_modelprocess_modeluser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("datasourceId", models.IntegerField(default=-1)),
            ],
            options={
                "db_table": "tbl_metric",
            },
        ),
        migrations.RemoveField(
            model_name="modeldatasource",
            name="userId",
        ),
        migrations.RemoveField(
            model_name="modeldetector",
            name="processId",
        ),
        migrations.AddField(
            model_name="modeldatasource",
            name="user",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base_app.modeluser",
            ),
        ),
        migrations.AddField(
            model_name="modeldetector",
            name="process",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base_app.modelprocess",
            ),
        ),
        migrations.RemoveField(
            model_name="modeldetector",
            name="metricsList",
        ),
        migrations.RemoveField(
            model_name="modelprocess",
            name="metricsList",
        ),
        migrations.AddField(
            model_name="modeldetector",
            name="metricsList",
            field=models.ManyToManyField(to="base_app.modelmetrics"),
        ),
        migrations.AddField(
            model_name="modelprocess",
            name="metricsList",
            field=models.ManyToManyField(to="base_app.modelmetrics"),
        ),
    ]
