# Generated by Django 4.1.7 on 2023-04-07 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0002_modeldatasource_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeldatasource",
            name="bucket",
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
