# Generated by Django 4.1.7 on 2023-04-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0003_modelmetrics_remove_modeldatasource_userid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modeldetector",
            name="metricsList",
        ),
        migrations.RemoveField(
            model_name="modelprocess",
            name="metricsList",
        ),
        migrations.AddField(
            model_name="modeldetector",
            name="metricList",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="modelprocess",
            name="metricList",
            field=models.TextField(default=""),
        ),
        migrations.DeleteModel(
            name="ModelMetrics",
        ),
    ]
