# Generated by Django 4.1.7 on 2023-04-18 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0004_remove_modeldetector_metricslist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelprocess",
            name="datasourceId",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base_app.modeldatasource",
            ),
        ),
    ]
