# Generated by Django 4.1.7 on 2023-04-18 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0005_alter_modelprocess_datasourceid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modelprocess",
            old_name="datasourceId",
            new_name="datasource",
        ),
    ]
