# Generated by Django 4.2 on 2023-04-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_rename_datasourceid_modelprocess_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldetector',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelprocess',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
