# Generated by Django 4.2 on 2023-04-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0007_modeldetector_status_modelprocess_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeldetector",
            name="exportCode",
            field=models.CharField(default="", max_length=250),
        ),
    ]
