# Generated by Django 4.2 on 2023-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0008_modeldetector_exportcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeldetector",
            name="lastUpdate",
            field=models.CharField(default=None, max_length=250),
        ),
    ]
