# Generated by Django 4.1.7 on 2023-05-05 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_modelalerthistory_alter_modeldetector_lastupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelalerthistory',
            name='alertAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 12, 40, 34, 414578)),
        ),
        migrations.AlterModelTable(
            name='modelalert',
            table='tbl_alert',
        ),
        migrations.AlterModelTable(
            name='modelalerthistory',
            table='tbl_alerthistory',
        ),
    ]
