# Generated by Django 4.1.7 on 2023-05-06 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_alter_modelalerthistory_alertat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelalert',
            old_name='anomalyValue',
            new_name='criticalTreshold',
        ),
        migrations.AddField(
            model_name='modelalert',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelalert',
            name='nearCriticalTreshold',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='modelalerthistory',
            name='alertType',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='modelalerthistory',
            name='alertAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 3, 23, 56, 530413)),
        ),
    ]
