# Generated by Django 4.1.7 on 2023-05-06 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_rename_anomalyvalue_modelalert_criticaltreshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelalert',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modelalerthistory',
            name='alertAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 4, 16, 39, 370862)),
        ),
        migrations.AlterField(
            model_name='modeldetector',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modelprocess',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
