# Generated by Django 4.1.7 on 2023-05-07 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_alter_modelalert_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeluser',
            name='password',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelalerthistory',
            name='alertAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 17, 43, 3, 693146)),
        ),
    ]
