# Generated by Django 4.1.7 on 2023-05-07 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_modeluser_password_alter_modelalerthistory_alertat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelalerthistory',
            name='alertAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 17, 44, 10, 743540)),
        ),
        migrations.AlterField(
            model_name='modeluser',
            name='password',
            field=models.CharField(default='', max_length=250),
        ),
    ]
