# Generated by Django 4.1.7 on 2023-05-19 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_alter_modelalerthistory_alertat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelalerthistory',
            name='alert',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='base_app.modelalert'),
        ),
        migrations.AddField(
            model_name='modelalerthistory',
            name='detector',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='base_app.modeldetector'),
        ),
        migrations.AlterField(
            model_name='modelalerthistory',
            name='alertAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 11, 35, 25, 411480)),
        ),
    ]
