# Generated by Django 4.1.7 on 2023-05-21 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_alter_modeluser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeluser',
            name='name',
        ),
        migrations.AlterField(
            model_name='modelalerthistory',
            name='alertAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 22, 39, 21, 390981)),
        ),
    ]
