# Generated by Django 4.1.7 on 2023-05-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0020_remove_modeluser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelalerthistory',
            name='alertAt',
            field=models.CharField(max_length=250),
        ),
    ]
