# Generated by Django 4.1.7 on 2023-05-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0022_modeldetector_lastscore_modeldetector_maxanomaly'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelalert',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modeldatasource',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modeldetector',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelprocess',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
